// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu1g0zL6xF7-h7bCJItSqggMIHy8VvfNA',
    appId: '1:905790811223:web:6cc80b4be0ec59f13f0712',
    messagingSenderId: '905790811223',
    projectId: 'flutter-chat-app-81e78',
    authDomain: 'flutter-chat-app-81e78.firebaseapp.com',
    storageBucket: 'flutter-chat-app-81e78.appspot.com',
    measurementId: 'G-S98XFHJ5BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ5vZkpQYM0cZ7PThh0Z8whajdJY4v9jc',
    appId: '1:905790811223:android:ab7742eea2af59603f0712',
    messagingSenderId: '905790811223',
    projectId: 'flutter-chat-app-81e78',
    storageBucket: 'flutter-chat-app-81e78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtSVBVrmCJRM1h4ze9EMMlk5VTYc6sjbk',
    appId: '1:905790811223:ios:a60d82497f11d3d53f0712',
    messagingSenderId: '905790811223',
    projectId: 'flutter-chat-app-81e78',
    storageBucket: 'flutter-chat-app-81e78.appspot.com',
    iosClientId: '905790811223-2c2kubscjh4gefg1ujdcio20rb4mio08.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtSVBVrmCJRM1h4ze9EMMlk5VTYc6sjbk',
    appId: '1:905790811223:ios:f9c5a87dbb9cd00c3f0712',
    messagingSenderId: '905790811223',
    projectId: 'flutter-chat-app-81e78',
    storageBucket: 'flutter-chat-app-81e78.appspot.com',
    iosClientId: '905790811223-l0virnbl0ar83dsrh9hovkjmc682bh64.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectChatApp.RunnerTests',
  );
}
